package ru.olegsvs.custombatterynotification;

import android.os.Parcel;
import android.os.Parcelable;
import android.util.Log;

import java.io.File;

/**
 * Created by olegsvs on 11.05.2017.
 */

public class BatteryManager implements Parcelable {
    private String capacityBattery = null; //path to capacity file
    private String statusBattery = null; //path to status file
    public boolean isSupport = false; //support for capacityBattery & statusBattery paths

    BatteryManager(String typeBattery, String stateBattery) { //constructor with battery parameters paths
        if((typeBattery != null) && (stateBattery != null)) //check parameters for not null
            if(isSupportCheck(typeBattery) && isSupportCheck(stateBattery)) { //check paths 
                this.capacityBattery = typeBattery; //set values
                this.statusBattery = stateBattery;
            } else isSupport = false; //if not supported return false
    }

    protected BatteryManager(Parcel in) { //autogenerated parcelable constructor
        capacityBattery = in.readString();
        statusBattery = in.readString();
        isSupport = in.readByte() != 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) { //autogenerated 
        dest.writeString(capacityBattery);
        dest.writeString(statusBattery);
        dest.writeByte((byte) (isSupport ? 1 : 0));
    }

    @Override
    public int describeContents() { //autogenerated 
        return 0;
    }

    public static final Creator<BatteryManager> CREATOR = new Creator<BatteryManager>() { //autogenerated 
        @Override
        public BatteryManager createFromParcel(Parcel in) {
            return new BatteryManager(in);
        }

        @Override
        public BatteryManager[] newArray(int size) {
            return new BatteryManager[size];
        }
    };

    private boolean isSupportCheck(String capacityBattery) { //check support for path
        File file = new File(capacityBattery);
        if (file.exists()) {
            Log.w(SettingsActivity.TAG, "isSupportCheck:  " + capacityBattery + " exists!");
            return isSupport = true;
        }
        Log.w(SettingsActivity.TAG, "isSupportCheck:  " + capacityBattery + " NOT exists!");
        return isSupport = false;
    }

    public String getCapacity() { //return capacity value
        if(isSupport) {
            File file = new File(capacityBattery); 
                return OneLineReader.getValue(file);
        }
        return  "0";
    }

    public String getState() { //return status value
        if(isSupport) {
            File file = new File(statusBattery);
            return " " + OneLineReader.getValue(file);
        }
        return  " - ";
    }
}
